MODEL:
  META_ARCHITECTURE: "TransformerDetectorSD21"
  MASK_ON: False
  # vae encoder input [-1,1] normalization
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD:  [127.5, 127.5, 127.5]
  BACKBONE:
    NAME: 
  RESNETS:
    STRIDE_IN_1X1: 
    OUT_FEATURES: 
  TRANSFORMER:
    ENABLED: True
    INFERENCE_TH_TEST: 0.45
SOLVER:
  WEIGHT_DECAY: 1e-4
  OPTIMIZER: "ADAMW"
  LR_BACKBONE_NAMES: 
  LR_LINEAR_PROJ_NAMES: 
  LR_LINEAR_PROJ_MULT:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
INPUT:
  HFLIP_TRAIN: False
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1600
  MAX_SIZE_TEST: 1824
  CROP:
    ENABLED: False
    CROP_INSTANCE: False
    SIZE: [0.1, 0.1]
  FORMAT: "RGB"
  # PHO
  FIX_SIZE: True
  FIX_SIZE_H: 512 
  FIX_SIZE_W: 512 