_BASE_: "Base-Pretrain-Polygon.yaml"
MODEL:
  # WEIGHTS: "weights/resnet50-19c8e357.pth"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  AMP:
    ENABLED: False
  IMS_PER_BATCH: 2
  GRAD_ACCUM_STEPS: 12
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (340000,)
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/pretrain/syntext_to_totaltext/pho_s18_gpu1_TESTR_R50detectron_lr1e4_bs2_accum12"

LOG_ARGS:
  LOG_NUM_IMG: 2
  LOG_EVERY_N: 1000
