_BASE_: "Base-Pretrain-Polygon.yaml"

MODEL:
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
  
  DIFFUSION:
    BACKBONE: "SD21"
    FREEZE_COMPONENT: 'ALL'
    EXTRACT_FEAT: True

SOLVER:
  AMP:
    ENABLED: False
  IMS_PER_BATCH: 4
  GRAD_ACCUM_STEPS: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 
  WARMUP_ITERS: 0
  STEPS: (340000,)
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "output/pretrain/totaltext/pho_s18_gpu3_TESTR_SD21_lr1e4_bs4_accum8"

LOG_ARGS:
  LOG_NUM_IMG: 2
  LOG_EVERY_N: 5000

